In [22]:
# 1 dimensional array
import numpy as np
list_1 = [20,50,60,78,60,80,100,200]
list_1

[20, 50, 60, 78, 60, 80, 100, 200]

In [23]:
# let's create a numpy array from the list"my_list"
my_numpy_list = np.array(list_1)
my_numpy_list

array([ 20,  50,  60,  78,  60,  80, 100, 200])

In [24]:
# to know the type
type(my_numpy_list)

numpy.ndarray

In [25]:
#multi dimensional array
my_matrix = np.array([[4,5,6],[8,9,6]])
my_matrix

array([[4, 5, 6],
       [8, 9, 6]])

In [26]:
# write a code that creates the following 2*4 numpy array
#[[3 7 9 3]
#[4 3 2 2]]
a = np.array([[3,7,9,3],[4,3,2,2]])
a

array([[3, 7, 9, 3],
       [4, 3, 2, 2]])

In [31]:
# leverage numpy buint in methods and functions
# rand() uniform distribution between 0 and 1
x = np.random.rand(30)

x

array([0.31080183, 0.61368176, 0.68505463, 0.93328454, 0.27835458,
       0.99082   , 0.78504427, 0.71609294, 0.0874123 , 0.49384074,
       0.84692001, 0.9221664 , 0.29465627, 0.13601903, 0.23152765,
       0.44008683, 0.32475553, 0.35442125, 0.4824361 , 0.1427911 ,
       0.88023385, 0.30877817, 0.699081  , 0.73694356, 0.35578428,
       0.34657013, 0.76752841, 0.96620219, 0.61646152, 0.38486733])

In [33]:
#creating a matrix of random number
x = np.random.rand(2,4)
x

array([[0.56314063, 0.31468572, 0.5893674 , 0.70523451],
       [0.55297358, 0.00391445, 0.79937423, 0.28551708]])

In [35]:
# randint is used to generate random integer between upper and lower bounds
x = np.random.randint(9)
x

3

In [36]:
# randint can be used to generate number of random interger
x = np.random.randint(1,100,20)
x

array([83, 12, 85, 36, 60, 34, 72, 65, 48, 49, 22, 78, 77, 82, 66, 93, 18,
       60, 84, 92])

In [38]:
# np.arange creates an evenly spaced values within a given interval
x = np.arange(1,50)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [40]:
# create a diagonal of ones and zeros everywhere else
x = np.eye(8)
x

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [43]:
# Matrix of ones
x = np.ones((8,10))
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [44]:
# Array of zeros
x = np.zeros((5,5))
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [30]:
#write a code takes a positive integer x from the user and creates a 1*10 array with random number number ranging form 0to x
x = int(input("Enter a positive integer value = "))
x = np.random.randint(1,x,10)
x

Enter a positive integer value = 200


array([117,  12,  44,  81, 128,  46, 189, 154, 180, 135])

In [ ]:
# 3 perform mathematical operations in numpy


In [48]:
# np.arange() returns an evenly spaced values within a given interval
a = np.arange(1,10)
a


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
b = np.arange(1,10)
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
# Add 2 numpy arrays together
sum = a+b
sum

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [51]:
#square root
square = np.square(a)  # or it can be calculate as a**2
square

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [52]:
sqrt = np.sqrt(square)
sqrt

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [53]:
c = np.exp(a)
c

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [57]:
'''MINI CHALLENGE #3:

Given the X and Y values below, obtain the distance between them
X = [5, 7, 20]
Y = [9, 15, 4]'''

x = np.array([5,7,20])
y = np.array([9,15,4])
z = np.sqrt(x**2+y**2)
z

array([10.29563014, 16.55294536, 20.39607805])

In [59]:
# 4=arrays slicing and indexing
# Access specific index from the numpy array
list_1 = np.array([20,50,60,78,60,80,100,200])
list_1

array([ 20,  50,  60,  78,  60,  80, 100, 200])

In [61]:
list_1[0]
list_1[0:5]

array([20, 50, 60, 78, 60])

In [62]:
# Broadcasting, altering several values in a numpy array at once
list_1[0:3] = 5
list_1

array([  5,   5,   5,  78,  60,  80, 100, 200])

In [64]:
# Let's define a two dimensional numpy array
matrix = np.random.randint(1,10,(4,4))
matrix

array([[9, 8, 4, 9],
       [8, 3, 9, 9],
       [9, 2, 8, 3],
       [1, 8, 2, 7]])

In [65]:
# Get a row from a mtrix
matrix[1]

array([8, 3, 9, 9])

In [66]:
# Get a row from a mtrix
matrix[2][0]

9

In [68]:
'''MINI CHALLENGE #4:

In the following matrix, replace the last row with 0'''

x = np.array([[2 ,30 ,20 ,-2, -4],
            [3 ,4 , 40 ,-3 ,-2],
            [-3 ,4 ,-6, 90, 10],
            [25, 45 ,34 ,22, 12],
            [13 ,24, 22 ,32 ,37]])
x[4]=0
x

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

In [73]:
#5 element selection
matrix = np.random.randint(1,10,(5,5))
matrix

array([[5, 4, 5, 3, 1],
       [5, 6, 2, 7, 6],
       [5, 6, 4, 2, 7],
       [2, 1, 9, 2, 4],
       [9, 1, 9, 5, 1]])

In [74]:
matrix[matrix>5]

array([6, 7, 6, 6, 7, 9, 9, 9])

In [75]:
# Obtain odd elements only
new_matrix = matrix[matrix %2 ==1]
new_matrix

array([5, 5, 3, 1, 5, 7, 5, 7, 1, 9, 9, 1, 9, 5, 1])

In [ ]:
'''MINI CHALLENGE #5:

In the following matrix, replace negative elements by 0 and replace odd elements with -2
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]'''

In [76]:

x = np.array([[2 ,30 ,20, -2 ,-4],
            [3 ,4 , 40, -3, -2],
            [-3, 4, -6, 90, 10],
            [25 ,45 ,4, 22, 12],
            [13, 24 ,22, 32, 37]])
x

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45,  4, 22, 12],
       [13, 24, 22, 32, 37]])

In [78]:
x[x<0] = 0
x[x%2==1] =-2
x

array([[ 2, 30, 20,  0,  0],
       [-2,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [-2, -2,  4, 22, 12],
       [-2, 24, 22, 32, -2]])