In [13]:
# 1 dimensional array
import numpy as np
list_1 = [20,50,60,78,60,80,100,200]
list_1

[20, 50, 60, 78, 60, 80, 100, 200]

In [14]:
# let's create a numpy array from the list"my_list"
my_numpy_list = np.array(list_1)
my_numpy_list

array([ 20,  50,  60,  78,  60,  80, 100, 200])

In [15]:
# to know the type
type(my_numpy_list)

numpy.ndarray

In [16]:
#multi dimensional array
my_matrix = np.array([[4,5,6],[8,9,6]])
my_matrix

array([[4, 5, 6],
       [8, 9, 6]])

In [17]:
# write a code that creates the following 2*4 numpy array
#[[3 7 9 3]
#[4 3 2 2]]
a = np.array([[3,7,9,3],[4,3,2,2]])
a

array([[3, 7, 9, 3],
       [4, 3, 2, 2]])

In [18]:
# leverage numpy buint in methods and functions
# rand() uniform distribution between 0 and 1
x = np.random.rand(30)

x

array([0.5922572 , 0.49205145, 0.8268003 , 0.92530289, 0.80643137,
       0.9536342 , 0.05981907, 0.745681  , 0.76597994, 0.01141808,
       0.34760072, 0.83198478, 0.48629194, 0.4092163 , 0.60624984,
       0.17528353, 0.04283633, 0.77228426, 0.78735593, 0.31668642,
       0.42988854, 0.00603803, 0.76326513, 0.67582768, 0.84044777,
       0.32713687, 0.73918093, 0.56005582, 0.97974255, 0.98182236])

In [19]:
#creating a matrix of random number
x = np.random.rand(2,4)
x

array([[0.03031289, 0.38712633, 0.20146842, 0.53020515],
       [0.33459524, 0.62185222, 0.89234543, 0.1085899 ]])

In [20]:
# randint is used to generate random integer between upper and lower bounds
x = np.random.randint(9)
x

8

In [21]:
# randint can be used to generate number of random interger
x = np.random.randint(1,100,20)
x

array([28, 91, 53, 11, 65, 26, 82, 55, 76, 30,  2, 82, 42,  9, 25, 96, 83,
       40, 62, 31])

In [22]:
# np.arange creates an evenly spaced values within a given interval
x = np.arange(1,50)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [23]:
# create a diagonal of ones and zeros everywhere else
x = np.eye(8)
x

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [24]:
# Matrix of ones
x = np.ones((8,10))
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [25]:
# Array of zeros
x = np.zeros((5,5))
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
#write a code takes a positive integer x from the user and creates a 1*10 array with random number number ranging form 0to x
x = int(input("Enter a positive integer value = "))
x = np.random.randint(1,x,10)
x

Enter a positive integer value = 50


array([15,  9, 21, 30, 13, 36,  2, 28, 36, 11])

In [27]:
# 3 perform mathematical operations in numpy


In [28]:
# np.arange() returns an evenly spaced values within a given interval
a = np.arange(1,10)
a


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
b = np.arange(1,10)
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
# Add 2 numpy arrays together
sum = a+b
sum

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [31]:
#square root
square = np.square(a)  # or it can be calculate as a**2
square

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [32]:
sqrt = np.sqrt(square)
sqrt

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [33]:
c = np.exp(a)
c

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [34]:
'''MINI CHALLENGE #3:

Given the X and Y values below, obtain the distance between them
X = [5, 7, 20]
Y = [9, 15, 4]'''

x = np.array([5,7,20])
y = np.array([9,15,4])
z = np.sqrt(x**2+y**2)
z

array([10.29563014, 16.55294536, 20.39607805])

In [35]:
# 4=arrays slicing and indexing
# Access specific index from the numpy array
list_1 = np.array([20,50,60,78,60,80,100,200])
list_1

array([ 20,  50,  60,  78,  60,  80, 100, 200])

In [36]:
list_1[0]
list_1[0:5]

array([20, 50, 60, 78, 60])

In [37]:
# Broadcasting, altering several values in a numpy array at once
list_1[0:3] = 5
list_1

array([  5,   5,   5,  78,  60,  80, 100, 200])

In [38]:
# Let's define a two dimensional numpy array
matrix = np.random.randint(1,10,(4,4))
matrix

array([[3, 7, 9, 7],
       [3, 9, 7, 3],
       [1, 1, 8, 9],
       [5, 9, 7, 8]])

In [39]:
# Get a row from a mtrix
matrix[1]

array([3, 9, 7, 3])

In [40]:
# Get a row from a mtrix
matrix[2][0]

1

In [41]:
'''MINI CHALLENGE #4:

In the following matrix, replace the last row with 0'''

x = np.array([[2 ,30 ,20 ,-2, -4],
            [3 ,4 , 40 ,-3 ,-2],
            [-3 ,4 ,-6, 90, 10],
            [25, 45 ,34 ,22, 12],
            [13 ,24, 22 ,32 ,37]])
x[4]=0
x

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

In [42]:
#5 element selection
matrix = np.random.randint(1,10,(5,5))
matrix

array([[9, 9, 8, 3, 2],
       [6, 4, 7, 5, 9],
       [4, 8, 7, 1, 4],
       [4, 5, 8, 7, 7],
       [9, 2, 9, 5, 5]])

In [43]:
matrix[matrix>5]

array([9, 9, 8, 6, 7, 9, 8, 7, 8, 7, 7, 9, 9])

In [44]:
# Obtain odd elements only
new_matrix = matrix[matrix %2 ==1]
new_matrix

array([9, 9, 3, 7, 5, 9, 7, 1, 5, 7, 7, 9, 9, 5, 5])

In [45]:
'''MINI CHALLENGE #5:

In the following matrix, replace negative elements by 0 and replace odd elements with -2
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]'''

'MINI CHALLENGE #5:\n\nIn the following matrix, replace negative elements by 0 and replace odd elements with -2\nX = [2 30 20 -2 -4]\n    [3 4  40 -3 -2]\n    [-3 4 -6 90 10]\n    [25 45 34 22 12]\n    [13 24 22 32 37]'

In [46]:

x = np.array([[2 ,30 ,20, -2 ,-4],
            [3 ,4 , 40, -3, -2],
            [-3, 4, -6, 90, 10],
            [25 ,45 ,4, 22, 12],
            [13, 24 ,22, 32, 37]])
x

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45,  4, 22, 12],
       [13, 24, 22, 32, 37]])

In [47]:
x[x<0] = 0
x[x%2==1] =-2
x

array([[ 2, 30, 20,  0,  0],
       [-2,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [-2, -2,  4, 22, 12],
       [-2, 24, 22, 32, -2]])

In [48]:
# 6 understand pandas and fundamentals
import pandas as pd
bank_data_df = pd.DataFrame({'name':['hari','shuna','bal','kabita'],
                            'address':['kathmandu','lalitpur','kapan','bhaktapur'],
                            'phone':[9562,8945,2369,7456]})
bank_data_df

name    address  phone
0    hari  kathmandu   9562
1   shuna   lalitpur   8945
2     bal      kapan   2369
3  kabita  bhaktapur   7456

In [49]:
bank_data_df.head(3)

name    address  phone
0   hari  kathmandu   9562
1  shuna   lalitpur   8945
2    bal      kapan   2369

In [50]:
bank_data_df.tail(2)

name    address  phone
2     bal      kapan   2369
3  kabita  bhaktapur   7456

In [51]:
'''MINI CHALLENGE #6:

A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' 
that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
Calculate the total value of the porfolio including all stocks'''


portfolio_df = pd.DataFrame({'stock ticker symbols': ['upper','nica','snbl'],
                            'price per share [Rs]':[200,500,400],
                            'number of share': [20,50,5]})
portfolio_df

stock ticker symbols  price per share [Rs]  number of share
0                upper                   200               20
1                 nica                   500               50
2                 snbl                   400                5

In [52]:
total_value = portfolio_df['price per share [Rs]']*portfolio_df['number of share']
total_value

0     4000
1    25000
2     2000
dtype: int64

In [53]:
#7 pandas with csv and html
house_price_df = pd.read_html("https://www.livingin-canada.com/house-prices-canada.html")
house_price_df[0]

City  \
0                                      Vancouver, BC   
1                                       Toronto, Ont   
2                                        Ottawa, Ont   
3                                       Calgary, Alb   
4                                      Montreal, Que   
5                                        Halifax, NS   
6                                       Regina, Sask   
7                                    Fredericton, NB   
8  (adsbygoogle = window.adsbygoogle || []).push(...   

                                 Average House Price  \
0                                         $1,036,000   
1                                           $870,000   
2                                           $479,000   
3                                           $410,000   
4                                           $435,000   
5                                           $331,000   
6                                           $254,000   
7                                           $198,000   
8  (adsbygoogle = window.adsbygoogle || []).push(...   

                                     12 Month Change  
0                                           + 2.63 %  
1                                            +10.2 %  
2                                           + 15.4 %  
3                                            – 1.5 %  
4                                            + 9.3 %  
5                                            + 3.6 %  
6                                            – 3.9 %  
7                                            – 4.3 %  
8  (adsbygoogle = window.adsbygoogle || []).push(...

In [54]:
house_price_df[1]

Province  \
0                                    British Columbia   
1                                             Ontario   
2                                             Alberta   
3                                              Quebec   
4                                            Manitoba   
5                                        Saskatchewan   
6                                         Nova Scotia   
7                                Prince Edward Island   
8                             Newfoundland / Labrador   
9                                       New Brunswick   
10                                   Canadian Average   
11  (adsbygoogle = window.adsbygoogle || []).push(...   

                                  Average House Price  \
0                                            $736,000   
1                                            $594,000   
2                                            $353,000   
3                                            $340,000   
4                                            $295,000   
5                                            $271,000   
6                                            $266,000   
7                                            $243,000   
8                                            $236,000   
9                                            $183,000   
10                                           $488,000   
11  (adsbygoogle = window.adsbygoogle || []).push(...   

                                      12 Month Change  
0                                             + 7.6 %  
1                                             – 3.2 %  
2                                             – 7.5 %  
3                                             + 7.6 %  
4                                             – 1.4 %  
5                                             – 3.8 %  
6                                             + 3.5 %  
7                                             + 3.0 %  
8                                             – 1.6 %  
9                                             – 2.2 %  
10                                            – 1.3 %  
11  (adsbygoogle = window.adsbygoogle || []).push(...

In [75]:
# 8 pandas operation
#defining a data frame
bank_data_df = pd.DataFrame({'name':['hari','shuna','bal','kabita'],
                            'address':['kathmandu','lalitpur','kapan','bhaktapur'],
                            'phone':[9562,8945,2369,7456],
                            'saving':[50000,60000,20000,65000]})
bank_data_df

name    address  phone  saving
0    hari  kathmandu   9562   50000
1   shuna   lalitpur   8945   60000
2     bal      kapan   2369   20000
3  kabita  bhaktapur   7456   65000

In [76]:
#filtering
new_data_df = bank_data_df[bank_data_df['saving']>=50000]
new_data_df

name    address  phone  saving
0    hari  kathmandu   9562   50000
1   shuna   lalitpur   8945   60000
3  kabita  bhaktapur   7456   65000

In [77]:
# deleting
del bank_data_df['name']
bank_data_df

address  phone  saving
0  kathmandu   9562   50000
1   lalitpur   8945   60000
2      kapan   2369   20000
3  bhaktapur   7456   65000

In [78]:
#9 pandas with function
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [80]:
# increase the net worth by 20%
def networth_update(balance):
    return balance *1.2
bank_client_df['Net worth [$]'].apply(networth_update)

0     4200.0
1    34800.0
2    12000.0
3     2400.0
Name: Net worth [$], dtype: float64

In [81]:
#we can also calculate the length of the variables
bank_client_df['Bank Client Name'].apply(len)

0    6
1    5
2    5
3    4
Name: Bank Client Name, dtype: int64

In [83]:
'''MINI CHALLENGE #9:

Define a function that triples the stock prices and adds $200
Apply the function to the DataFrame
Calculate the updated total networth of all clients combined
'''
def networth_update(balance):
    return balance *3+200
bank_client_df['Net worth [$]'].apply(networth_update)

0    10700
1    87200
2    30200
3     6200
Name: Net worth [$], dtype: int64

In [84]:
# 10 sorting and ordering with pandas
# Let's define a dataframe as follows:
import pandas as pd
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [85]:
# You can sort the values in the dataframe according tao number of years with bank
bank_client_df.sort_values(by = 'Years with bank')

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

In [86]:
# Note that nothing changed in memory! you have to make sure that inplace is set to True
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [88]:
# Set inplace = True to ensure that change has taken place in memory 
bank_client_df.sort_values(by = 'Years with bank', inplace = True)
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

In [89]:
#TASK #11: PERFORM CONCATENATING AND MERGING WITH PANDAS
df1 = pd.DataFrame({'A':['A1','A2','A3','A4'],
                   'B':['B1','B2','B3','B4'],
                   'C':['C1','C2','C3','C4'],
                   'D':['D1','D2','D3','D4']},
                     index = [1,2,3,4])
df1

A   B   C   D
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4

In [90]:
df2 = pd.DataFrame({'A':['A5','A6','A7','A8'],
                   'B':['B5','B6','B7','B8'],
                   'C':['C5','C6','C7','C8'],
                   'D':['D5','D6','D7','D8']},
                     index = [5,6,7,8])
df2

A   B   C   D
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7
8  A8  B8  C8  D8

In [91]:
df3 = pd.DataFrame({'A':['A9','A10','A11','A12'],
                   'B':['B9','B10','B11','B12'],
                   'C':['C9','C10','C11','C12'],
                   'D':['D9','D10','D11','D12']},
                     index = [9,10,11,12])
df3

A    B    C    D
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11
12  A12  B12  C12  D12

In [92]:
pd.concat([df1,df2,df3])

A    B    C    D
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11
12  A12  B12  C12  D12

In [ ]:
TASK #12: PROJECT AND CONCLUDING REMARKS
'''Define a dataframe named 'Bank_df_1' that contains the first and last names for 5 bank clients with IDs = 1, 2, 3, 4, 5
Assume that the bank got 5 new clients, define another dataframe named 'Bank_df_2' that contains a new clients with IDs = 6, 7, 8, 9, 10
Let's assume we obtained additional information (Annual Salary) about all our bank customers (10 customers)
Concatenate both 'bank_df_1' and 'bank_df_2' dataframes
Merge client names and their newly added salary information using the 'Bank Client ID'
Let's assume that you became a new client to the bank
Define a new DataFrame that contains your information such as client ID (choose 11), first name, last name, and annual salary.
Add this new dataframe to the original dataframe 'bank_df_all'.'''

In [96]:
import pandas as pd
raw_data = {'Bank Client ID': ['1','2','3','4','5'],
           'First name': ['Sunita','Mina','Bina','Sinu','Hina'],
           'Last name':['Basi','Lama','Shrestha','Adikhari','Pandey']}
bank_df1 = pd.DataFrame(raw_data,columns = ['Bank Client ID','First name','Last name'])
bank_df1

Bank Client ID First name Last name
0              1     Sunita      Basi
1              2       Mina      Lama
2              3       Bina  Shrestha
3              4       Sinu  Adikhari
4              5       Hina    Pandey

In [97]:
raw_data = {'Bank Client ID': ['6','7','8','9','10'],
           'First name': ['Hem','Mintu','Ben','Santa','Crane'],
           'Last name':['Bob','sharma','Shr','Adi','Pan']}
bank_df2 = pd.DataFrame(raw_data,columns = ['Bank Client ID','First name','Last name'])
bank_df2

Bank Client ID First name Last name
0              6        Hem       Bob
1              7      Mintu    sharma
2              8        Ben       Shr
3              9      Santa       Adi
4             10      Crane       Pan

In [98]:
bank_client_all = pd.concat([bank_df1,bank_df2])
bank_client_all

Bank Client ID First name Last name
0              1     Sunita      Basi
1              2       Mina      Lama
2              3       Bina  Shrestha
3              4       Sinu  Adikhari
4              5       Hina    Pandey
0              6        Hem       Bob
1              7      Mintu    sharma
2              8        Ben       Shr
3              9      Santa       Adi
4             10      Crane       Pan

In [102]:
raw_data =({'Bank Client ID':['1','2','3','4','5','6','7','8','9','10'],
            'Annual Salary [Rs]':[50000,60000,50000,45000,80000,90000,56000,55000,23000,75000]})
salary_data = pd.DataFrame(raw_data,columns = ['Bank Client ID','Annual Salary [Rs]'])
salary_data

Bank Client ID  Annual Salary [Rs]
0              1               50000
1              2               60000
2              3               50000
3              4               45000
4              5               80000
5              6               90000
6              7               56000
7              8               55000
8              9               23000
9             10               75000

In [105]:
bank_client_all = pd.merge(bank_client_all,salary_data,on = 'Bank Client ID')
bank_client_all

Bank Client ID First name Last name  Annual Salary [Rs]
0              1     Sunita      Basi               50000
1              2       Mina      Lama               60000
2              3       Bina  Shrestha               50000
3              4       Sinu  Adikhari               45000
4              5       Hina    Pandey               80000
5              6        Hem       Bob               90000
6              7      Mintu    sharma               56000
7              8        Ben       Shr               55000
8              9      Santa       Adi               23000
9             10      Crane       Pan               75000

In [106]:
raw_data = ({'Bank Client ID':['11'],'First name':['John'],'Last name':['Bob'],'Annual Salary [Rs]': [80000]})
new_data = pd.DataFrame(raw_data,columns = ['Bank Client ID','First name','Last name','Annual Salary [Rs]'])
new_data

Bank Client ID First name Last name  Annual Salary [Rs]
0             11       John       Bob               80000

In [107]:
final_df = pd.concat([bank_client_all,new_data],axis = 0)
final_df

Bank Client ID First name Last name  Annual Salary [Rs]
0              1     Sunita      Basi               50000
1              2       Mina      Lama               60000
2              3       Bina  Shrestha               50000
3              4       Sinu  Adikhari               45000
4              5       Hina    Pandey               80000
5              6        Hem       Bob               90000
6              7      Mintu    sharma               56000
7              8        Ben       Shr               55000
8              9      Santa       Adi               23000
9             10      Crane       Pan               75000
0             11       John       Bob               80000

In [108]:
final_df.columns

Index(['Bank Client ID', 'First name', 'Last name', 'Annual Salary [Rs]'], dtype='object')